# Generated by Django 5.0.2 on 2024-02-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_failed_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
